language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"

os:
  - linux
  - osx

services:
  - docker

addons:
  apt:
    packages:
      - libnotify-bin
      - sshpass

cache: pip

install:
    - ./bin/build-dev

script:
    - ./bin/test

after_success:
    - coveralls