language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"

services:
  - docker

addons:
    apt:
        packages:
            - libnotify-bin
            - shellcheck
            - sshpass

cache: pip

install:
    - ./bin/build-dev

script:
    - ./bin/test

after_success:
    - coveralls