language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"

cache: pip

addons:
    apt:
        packages:
            - libnotify-bin

install:
    - ./bin/build-dev

script:
    - ./bin/test

after_success:
    - coveralls